"""Validated domain contracts shared by every MedBoard component."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated, Self
from uuid import uuid4

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    JsonValue,
    StringConstraints,
    field_validator,
    model_validator,
)

NonEmptyString = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
ConfidenceScore = Annotated[float, Field(ge=0.0, le=1.0)]

REPORT_DISCLAIMER = (
    "This output is generated by an experimental AI clinical decision-support "
    "system and requires review by a qualified healthcare professional."
)


def utc_now() -> datetime:
    """Return a timezone-aware timestamp for audit records."""
    return datetime.now(UTC)


def new_id(prefix: str) -> str:
    """Create a collision-resistant, readable identifier."""
    return f"{prefix}-{uuid4().hex[:12].upper()}"


class ContractModel(BaseModel):
    """Strict base for all data crossing an agent or persistence boundary."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
        use_enum_values=False,
    )


class AgentStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class MessageType(StrEnum):
    CLAIM = "claim"
    CHALLENGE = "challenge"
    REQUEST = "request"
    RESPONSE = "response"
    WARNING = "warning"
    REVISION = "revision"


class EvidenceType(StrEnum):
    HISTORY = "history"
    SYMPTOM = "symptom"
    LAB = "lab"
    MEDICATION = "medication"
    EXAMINATION = "examination"
    RETRIEVED = "retrieved"
    HUMAN = "human"
    RULE = "rule"


class HumanStatus(StrEnum):
    NOT_REQUESTED = "not_requested"
    WAITING_FOR_HUMAN = "waiting_for_human"
    APPROVED = "approved"
    REJECTED = "rejected"
    MORE_INFORMATION = "more_information"
    REQUEST_REVISION = "request_revision"


class CriticDecision(StrEnum):
    ACCEPT = "accept"
    REVISE = "revise"


class Severity(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TriageLevel(StrEnum):
    ROUTINE = "routine"
    PRIORITY = "priority"
    URGENT = "urgent"
    EMERGENCY = "emergency"


class TraceEventType(StrEnum):
    WORKFLOW_STARTED = "workflow_started"
    WORKFLOW_COMPLETED = "workflow_completed"
    AGENT_STARTED = "agent_started"
    AGENT_COMPLETED = "agent_completed"
    AGENT_FAILED = "agent_failed"
    ROUTING_DECISION = "routing_decision"
    TOOL_CALLED = "tool_called"
    INTERRUPTED = "interrupted"
    RESUMED = "resumed"


class LabObservation(ContractModel):
    """A supplied laboratory value; units are never inferred."""

    name: NonEmptyString
    value: float | int | NonEmptyString
    unit: NonEmptyString | None = None
    reference_range: NonEmptyString | None = None


class MedicalCaseInput(ContractModel):
    """Structured input accepted from a synthetic or de-identified case."""

    case_id: str = Field(default_factory=lambda: new_id("CASE"), frozen=True)
    synthetic: bool = True
    age: int | None = Field(default=None, ge=0, le=125)
    biological_sex: NonEmptyString | None = None
    chief_complaint: NonEmptyString
    narrative: str = ""
    symptoms: list[NonEmptyString] = Field(default_factory=list)
    history: list[NonEmptyString] = Field(default_factory=list)
    medications: list[NonEmptyString] = Field(default_factory=list)
    allergies: list[NonEmptyString] = Field(default_factory=list)
    laboratory_values: list[LabObservation] = Field(default_factory=list)


class NormalizedCase(ContractModel):
    """Agent-normalized case facts without inferred or invented information."""

    age: int | None = Field(default=None, ge=0, le=125)
    biological_sex: NonEmptyString | None = None
    chief_complaint: NonEmptyString
    normalized_symptoms: list[NonEmptyString] = Field(default_factory=list)
    history: list[NonEmptyString] = Field(default_factory=list)
    medications: list[NonEmptyString] = Field(default_factory=list)
    allergies: list[NonEmptyString] = Field(default_factory=list)
    laboratory_values: list[LabObservation] = Field(default_factory=list)


class Evidence(ContractModel):
    """Auditable fact that claims can reference by ID."""

    evidence_id: str = Field(default_factory=lambda: new_id("EV"), frozen=True)
    evidence_type: EvidenceType
    name: NonEmptyString
    value: JsonValue
    source: NonEmptyString
    confidence: ConfidenceScore = 1.0
    metadata: dict[str, JsonValue] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=utc_now)

    @field_validator("evidence_id")
    @classmethod
    def validate_evidence_id(cls, value: str) -> str:
        if not value.startswith("EV-"):
            raise ValueError("evidence_id must start with 'EV-'")
        return value

    @field_validator("created_at")
    @classmethod
    def normalize_created_at(cls, value: datetime) -> datetime:
        return _as_utc(value)


class Claim(ContractModel):
    """An agent assertion with explicit supporting and contradicting evidence."""

    claim_id: str = Field(default_factory=lambda: new_id("CLM"), frozen=True)
    agent: NonEmptyString
    statement: NonEmptyString
    evidence_ids: list[str] = Field(default_factory=list)
    contradicting_evidence_ids: list[str] = Field(default_factory=list)
    confidence: ConfidenceScore

    @field_validator("claim_id")
    @classmethod
    def validate_claim_id(cls, value: str) -> str:
        if not value.startswith("CLM-"):
            raise ValueError("claim_id must start with 'CLM-'")
        return value

    @field_validator("evidence_ids", "contradicting_evidence_ids")
    @classmethod
    def validate_evidence_references(cls, values: list[str]) -> list[str]:
        unique = _unique_strings(values)
        if any(not value.startswith("EV-") for value in unique):
            raise ValueError("claim evidence references must start with 'EV-'")
        return unique

    @model_validator(mode="after")
    def evidence_sets_must_not_overlap(self) -> Self:
        overlap = set(self.evidence_ids) & set(self.contradicting_evidence_ids)
        if overlap:
            raise ValueError("supporting and contradicting evidence cannot overlap")
        return self


class AgentMessage(ContractModel):
    """A structured, auditable agent-to-agent communication."""

    message_id: str = Field(default_factory=lambda: new_id("MSG"), frozen=True)
    sender: NonEmptyString
    recipient: NonEmptyString
    message_type: MessageType
    content: NonEmptyString
    evidence_ids: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=utc_now)

    @field_validator("message_id")
    @classmethod
    def validate_message_id(cls, value: str) -> str:
        if not value.startswith("MSG-"):
            raise ValueError("message_id must start with 'MSG-'")
        return value

    @field_validator("evidence_ids")
    @classmethod
    def validate_message_evidence(cls, values: list[str]) -> list[str]:
        unique = _unique_strings(values)
        if any(not value.startswith("EV-") for value in unique):
            raise ValueError("message evidence references must start with 'EV-'")
        return unique

    @field_validator("timestamp")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        return _as_utc(value)


class AgentOutput(ContractModel):
    """Common envelope returned by analytical agents."""

    agent: NonEmptyString
    status: AgentStatus
    summary: NonEmptyString
    claims: list[Claim] = Field(default_factory=list)
    missing_information: list[NonEmptyString] = Field(default_factory=list)
    questions_for_other_agents: list[NonEmptyString] = Field(default_factory=list)
    warnings: list[NonEmptyString] = Field(default_factory=list)

    @model_validator(mode="after")
    def claim_authors_must_match_agent(self) -> Self:
        if any(claim.agent != self.agent for claim in self.claims):
            raise ValueError("all claims must identify the producing agent")
        return self


class SupervisorPlan(ContractModel):
    case_categories: list[NonEmptyString] = Field(default_factory=list)
    initial_agents: list[NonEmptyString] = Field(default_factory=list)
    selected_specialists: list[NonEmptyString] = Field(default_factory=list)
    priority: TriageLevel = TriageLevel.ROUTINE
    reasoning: NonEmptyString

    @field_validator("initial_agents", "selected_specialists")
    @classmethod
    def agents_are_unique(cls, values: list[str]) -> list[str]:
        return _unique_strings(values)


class HistoryFindings(ContractModel):
    key_history: list[NonEmptyString] = Field(default_factory=list)
    risk_factors: list[NonEmptyString] = Field(default_factory=list)
    negative_findings: list[NonEmptyString] = Field(default_factory=list)
    missing_history: list[NonEmptyString] = Field(default_factory=list)
    possible_relevance: list[NonEmptyString] = Field(default_factory=list)
    output: AgentOutput


class SymptomFindings(ContractModel):
    normalized_symptoms: list[NonEmptyString] = Field(default_factory=list)
    symptom_clusters: list[NonEmptyString] = Field(default_factory=list)
    possible_systems: list[NonEmptyString] = Field(default_factory=list)
    red_flags: list[NonEmptyString] = Field(default_factory=list)
    missing_symptom_information: list[NonEmptyString] = Field(default_factory=list)
    output: AgentOutput


class LaboratoryFindings(ContractModel):
    abnormal_values: list[NonEmptyString] = Field(default_factory=list)
    important_patterns: list[NonEmptyString] = Field(default_factory=list)
    potential_implications: list[NonEmptyString] = Field(default_factory=list)
    missing_tests: list[NonEmptyString] = Field(default_factory=list)
    data_quality_warnings: list[NonEmptyString] = Field(default_factory=list)
    output: AgentOutput


class MedicationFindings(ContractModel):
    possible_adverse_effects: list[NonEmptyString] = Field(default_factory=list)
    potential_interactions: list[NonEmptyString] = Field(default_factory=list)
    duplicate_classes: list[NonEmptyString] = Field(default_factory=list)
    review_concerns: list[NonEmptyString] = Field(default_factory=list)
    output: AgentOutput


class DifferentialDiagnosis(ContractModel):
    hypothesis_id: str = Field(default_factory=lambda: new_id("HYP"), frozen=True)
    hypothesis: NonEmptyString
    supporting_evidence_ids: list[str] = Field(default_factory=list)
    contradicting_evidence_ids: list[str] = Field(default_factory=list)
    confidence: ConfidenceScore
    missing_evidence: list[NonEmptyString] = Field(default_factory=list)
    proposed_by: NonEmptyString = "differential"

    @field_validator("supporting_evidence_ids", "contradicting_evidence_ids")
    @classmethod
    def validate_hypothesis_evidence(cls, values: list[str]) -> list[str]:
        unique = _unique_strings(values)
        if any(not value.startswith("EV-") for value in unique):
            raise ValueError("hypothesis evidence references must start with 'EV-'")
        return unique


class SpecialistOpinion(ContractModel):
    opinion_id: str = Field(default_factory=lambda: new_id("OPN"), frozen=True)
    specialist: NonEmptyString
    assessment: NonEmptyString
    supported_hypotheses: list[str] = Field(default_factory=list)
    challenged_hypotheses: list[str] = Field(default_factory=list)
    alternative_hypotheses: list[NonEmptyString] = Field(default_factory=list)
    required_information: list[NonEmptyString] = Field(default_factory=list)
    critical_concerns: list[NonEmptyString] = Field(default_factory=list)
    confidence: ConfidenceScore


class RetrievedEvidence(ContractModel):
    retrieval_id: str = Field(default_factory=lambda: new_id("RAG"), frozen=True)
    document: NonEmptyString
    source: NonEmptyString
    section: NonEmptyString
    retrieved_text: NonEmptyString
    similarity_score: ConfidenceScore
    source_url: str | None = None


class Contradiction(ContractModel):
    contradiction_id: str = Field(default_factory=lambda: new_id("CON"), frozen=True)
    topic: NonEmptyString
    agent_a: NonEmptyString
    agent_b: NonEmptyString
    claim_ids: list[str] = Field(default_factory=list)
    resolved: bool = False
    resolution: NonEmptyString | None = None

    @model_validator(mode="after")
    def resolved_items_require_resolution(self) -> Self:
        if self.resolved and self.resolution is None:
            raise ValueError("resolved contradictions require a resolution")
        return self


class MissingInformationRequest(ContractModel):
    request_id: str = Field(default_factory=lambda: new_id("REQ"), frozen=True)
    information_needed: NonEmptyString
    requested_by: list[NonEmptyString]
    reason: NonEmptyString
    diagnostic_utility: ConfidenceScore = 0.5
    urgency: ConfidenceScore = 0.5
    evidence_ids: list[str] = Field(default_factory=list)

    @field_validator("requested_by")
    @classmethod
    def requesters_are_unique_and_present(cls, values: list[str]) -> list[str]:
        unique = _unique_strings(values)
        if not unique:
            raise ValueError("at least one requesting agent is required")
        return unique


class CriticReview(ContractModel):
    review_id: str = Field(default_factory=lambda: new_id("CRT"), frozen=True)
    decision: CriticDecision
    problems: list[NonEmptyString] = Field(default_factory=list)
    overlooked_hypotheses: list[NonEmptyString] = Field(default_factory=list)
    unsupported_claim_ids: list[str] = Field(default_factory=list)
    missing_evidence: list[NonEmptyString] = Field(default_factory=list)
    questions: list[NonEmptyString] = Field(default_factory=list)
    severity: Severity


class TriageResult(ContractModel):
    triage_level: TriageLevel
    red_flags: list[NonEmptyString] = Field(default_factory=list)
    reasoning: NonEmptyString
    recommended_escalation: NonEmptyString


class HumanReview(ContractModel):
    status: HumanStatus = HumanStatus.NOT_REQUESTED
    feedback: str | None = None
    reviewer: str | None = None
    updated_at: datetime = Field(default_factory=utc_now)

    @field_validator("updated_at")
    @classmethod
    def normalize_updated_at(cls, value: datetime) -> datetime:
        return _as_utc(value)


class FinalReport(ContractModel):
    report_id: str = Field(default_factory=lambda: new_id("RPT"), frozen=True)
    case_summary: NonEmptyString
    key_findings: list[NonEmptyString] = Field(default_factory=list)
    differential_considerations: list[DifferentialDiagnosis] = Field(default_factory=list)
    specialist_opinions: list[SpecialistOpinion] = Field(default_factory=list)
    retrieved_evidence: list[RetrievedEvidence] = Field(default_factory=list)
    disagreements: list[Contradiction] = Field(default_factory=list)
    missing_information: list[MissingInformationRequest] = Field(default_factory=list)
    triage: TriageResult
    review_priorities: list[NonEmptyString] = Field(default_factory=list)
    disclaimer: str = REPORT_DISCLAIMER

    @field_validator("disclaimer")
    @classmethod
    def preserve_required_disclaimer(cls, value: str) -> str:
        if value != REPORT_DISCLAIMER:
            raise ValueError("the mandatory decision-support disclaimer cannot be changed")
        return value


class AgentError(ContractModel):
    error_id: str = Field(default_factory=lambda: new_id("ERR"), frozen=True)
    agent: str | None = None
    error_type: NonEmptyString
    message: NonEmptyString
    severity: Severity = Severity.MEDIUM
    retryable: bool = False
    attempt: int = Field(default=1, ge=1)
    timestamp: datetime = Field(default_factory=utc_now)
    details: dict[str, JsonValue] = Field(default_factory=dict)

    @field_validator("timestamp")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        return _as_utc(value)


class TraceEvent(ContractModel):
    trace_id: str = Field(default_factory=lambda: new_id("TRC"), frozen=True)
    event_type: TraceEventType
    agent: str | None = None
    status: AgentStatus | None = None
    timestamp: datetime = Field(default_factory=utc_now)
    duration_ms: float | None = Field(default=None, ge=0)
    details: dict[str, JsonValue] = Field(default_factory=dict)

    @field_validator("timestamp")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        return _as_utc(value)


class TokenUsage(ContractModel):
    usage_id: str = Field(default_factory=lambda: new_id("TOK"), frozen=True)
    agent: NonEmptyString
    provider: NonEmptyString
    model: NonEmptyString
    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    estimated_cost: float = Field(default=0.0, ge=0)

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


def _unique_strings(values: list[str]) -> list[str]:
    """Deduplicate strings while retaining their first-seen order."""
    return list(dict.fromkeys(values))


def _as_utc(value: datetime) -> datetime:
    """Reject ambiguous timestamps and normalize aware values to UTC."""
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError("timestamp must be timezone-aware")
    return value.astimezone(UTC)
